# Generated by Django 2.2.2 on 2021-11-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_files/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('desctiption', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('Glory Tabernacle Summit', 'Glory Tabernacle Summit'), ('International Youth Summit', 'International Youth Summit'), ('Mixed Messages', 'Mixed Messages'), ('Spontaneous Sermos', 'Spontaneous Sermos'), ('Ministers Summit', 'Ministers Summit')], max_length=100)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
